text=input('пиши рускими буквами маленькими: ')
print()
#text = 'ах ты ж чьмо'
suma = (len(text))
space = (text.count(' '))
a = (text.count('а'))
b = (text.count('б'))
v = (text.count('в'))
g = (text.count('г'))
d = (text.count('д'))
e = (text.count('е'))
ee = (text.count('ё'))
j = (text.count('ж'))
z = (text.count('з'))
i = (text.count('и'))
iy = (text.count('й'))
k = (text.count('к'))
l = (text.count('л'))
m = (text.count('м'))
n = (text.count('н'))
o = (text.count('о'))
p = (text.count('п'))
r = (text.count('р'))
s = (text.count('с'))
t = (text.count('т'))
u = (text.count('у'))
f = (text.count('ф'))
x = (text.count('х'))
c = (text.count('с'))
ch = (text.count('ч'))
sh = (text.count('ш'))
shch = (text.count('щ'))
tz = (text.count('ъ'))
y = (text.count('ы'))
mz = (text.count('ь'))
ie = (text.count('э'))
iu = (text.count('ю'))
ia = (text.count('я'))

print('количество символов в тексте - %s' % suma)
print('пробелов - %s' % space)
print()
print('букв а - %s шт' % a)
print('букв б - %s шт' % b)
print('букв В - %s шт' % v)
print('букв г - %s шт' % g)
print('букв д - %s шт' % d)
print('букв е - %s шт' % e)
print('букв ё - %s шт' % ee)
print('букв ж - %s шт' % j)
print('букв з - %s шт' % z)
print('букв и - %s шт' % i)
print('букв й - %s шт' % iy)
print('букв к - %s шт' % k)
print('букв л - %s шт' % l)
print('букв м - %s шт' % m)
print('букв н - %s шт' % n)
print('букв о - %s шт' % o)
print('букв п - %s шт' % p)
print('букв р - %s шт' % r)
print('букв с - %s шт' % s)
print('букв т - %s шт' % t)
print('букв у - %s шт' % u)
print('букв ф - %s шт' % f)
print('букв х - %s шт' % x)
print('букв ц - %s шт' % c)
print('букв ч - %s шт' % ch)
print('букв ш - %s шт' % sh)
print('букв щ - %s шт' % shch)
print('букв ъ - %s шт' % tz)
print('букв ы - %s шт' % y)
print('букв ь - %s шт' % mz)
print('букв э - %s шт' % ie)
print('букв ю - %s шт' % iu)
print('букв я - %s шт' % ia)

